C: k-ex-09.ino File Reference
k-ex-09.ino File Reference
#include <krnl.h>
Macros
#define STKSIZE 100
#define TASKPRIO 10
Functions
void a ()
void d ()
void b ()
void c ()
void setup ()
void loop ()
void k_breakout ()
Variables
char stakA [STKSIZE]
char stakB [STKSIZE]
char stakC [STKSIZE]
struct k_t * pA
struct k_t * pB
struct k_t * pC
struct k_t * sem1
Macro Definition Documentation
STKSIZE
#define STKSIZE 100
Definition at line 13 of file k-ex-09.ino.
Referenced by setup().
TASKPRIO
#define TASKPRIO 10
Definition at line 15 of file k-ex-09.ino.
Referenced by setup().
Function Documentation
a()
void a ()
Definition at line 22 of file k-ex-09.ino.
References sem1.
Referenced by setup().
b()
void b ()
Definition at line 36 of file k-ex-09.ino.
References d().
Referenced by setup().
c()
void c ()
Definition at line 46 of file k-ex-09.ino.
References sem1.
Referenced by setup().
d()
void d ()
Definition at line 32 of file k-ex-09.ino.
Referenced by b().
k_breakout()
void k_breakout ()
Definition at line 80 of file k-ex-09.ino.
loop()
void loop ()
Definition at line 73 of file k-ex-09.ino.
setup()
void setup ()
Definition at line 57 of file k-ex-09.ino.
References a(), b(), c(), pA, pB, pC, sem1, stakA, stakB, stakC, STKSIZE, and TASKPRIO.
Variable Documentation
pA
struct k_t* pA
Definition at line 18 of file k-ex-09.ino.
Referenced by setup().
pB
struct k_t * pB
Definition at line 18 of file k-ex-09.ino.
Referenced by setup().
pC
struct k_t * pC
Definition at line 18 of file k-ex-09.ino.
Referenced by setup().
sem1
struct k_t* sem1
Definition at line 20 of file k-ex-09.ino.
Referenced by a(), c(), and setup().
stakA
char stakA[STKSIZE]
Definition at line 17 of file k-ex-09.ino.
Referenced by setup().
stakB
char stakB[STKSIZE]
Definition at line 17 of file k-ex-09.ino.
Referenced by setup().
stakC
char stakC[STKSIZE]
Definition at line 17 of file k-ex-09.ino.
Referenced by setup().